"""Change in regulation

Revision ID: 6b1040516620
Revises: 795c9d57f3e7
Create Date: 2023-09-03 20:41:20.635123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1040516620'
down_revision: Union[str, None] = '795c9d57f3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
